### PR TITLE
Properly handle DOCKER_CERT_PATH variable

### PR DESCRIPTION
**Pull request by sheerun**
This patch makes dockerode-options return proper options when DOCKER_CERT_PATH is set.

### CODE REVIEW

**Comment by lightsofapollo** [comment]
@sheerun This lgtm but can you either move the certs directory to something like example/certs or add it to `.npmignore` ?

**Comment by sheerun** [comment]
@lightsofapollo I did both

**Comment by lightsofapollo** [comment]
great thanks! I am going to merge this and add write permissions for you

**Comment by sheerun** [comment]
Thanks :)

**Comment by lightsofapollo** [comment]
hah forgot to merge

**Pull request merged**
